Faq page added
ReCoded-Org/capstone-turkey-react-paying-it-forward pull request #11
Opened 2022-04-07 18:26 UTC by mustafadurmaz

Faq page was created using tailwind css.

2022-04-08 09:07 UTC, Iseluin requested changes
Seems like you tried to use an external library called react-faq-component but did not even test your code to see if it works. Well, it does not.

1- Please do not use libraries like this before consulting with your team-lead and your teammates. 

2- You created a component but you did not even import it inside App.js to see if it works/shows something.

3- Capstone Project is a place where we show what we have learnt throughout the course. You can easily create the FAQ page we have designed with an illustration, some accordions and a header. So let us not go "the easy way" and create it ourselves.

4- The file structure is not quite right also, FAQ is a Page, so it must live inside src/pages/FAQ.jsx not in the components section.

Please start from scratch and create the FAQ page with help of Tailwind Elements Accordions and update your PR.

2022-04-08 09:07 UTC, Iseluin commented on package.json
> +    "react-faq-component": "^1.3.1",
We are not using this.

2022-04-08 09:07 UTC, Iseluin commented on src/components/Faq.jsx
> +export default Faq;
When you try to run this, it gives out an error. Did you try to run it on your machine ? You aren't even importing this to App.js to render this component.

2022-04-09 11:15 UTC, mustafadurmaz commented on package.json
> +    "react-faq-component": "^1.3.1",
react-faq-component removed

2022-04-09 11:18 UTC, mustafadurmaz commented on src/components/Faq.jsx
> +export default Faq;
App.js edited. The page is working now.

2022-04-10 22:06 UTC, Iseluin requested changes
Great work and dedication @mustafadurmaz , there are still few problems. Apart from what I wrote below;

1. Thank you for making your PR acceptible for the CI we just added. I like your determination and enthusiasm. 
2. When you code, please leave the Figma open and try to create the design we had there. The reason for us to use Figma is just that, for us to have a thing to look at when we code. You can see the colors we used in Figma, the font style and everything design related. You can even take the illustration from it by exporting it. So please try to utilize the power of it.

2022-04-10 22:06 UTC, Iseluin commented on .eslintrc.json
> +        "import/prefer-default-export": "off"
No exceptions please. Remove this and try to find a workaround without adding an exception here. You can ask help from your teammates about this.

2022-04-10 22:06 UTC, Iseluin commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.18",
Why did you add these dependencies ? I assume for using the illustration we have on the FAQ page but we don't need them. Please go to Figma design, click on the illustration we picked, click on the export and export it as an svg file. Then add that svg file inside a folder in the assets with the name of `images`. So the folder structure will be src/assets/images/<your-filename>. Then import it in your FAQ component and use it from there.

2022-04-10 22:06 UTC, Iseluin commented on src/App.jsx
> +import Faq from './pages/Faq';
Let's move the FAQ component into src/pages/FAQ/<your-filename>

2022-04-10 22:06 UTC, Iseluin commented on src/index.js
>  import * as serviceWorker from './serviceWorker';
Can you structure your imports like global imports at the top, then leave a blank line and add your local imports.

2022-04-10 22:06 UTC, Iseluin commented on src/pages/Faq.jsx
> +import imagefaq from '../images/image-faq.png';
Structure your imports as I mentioned above please.

2022-04-10 22:06 UTC, Iseluin commented on src/pages/Faq.jsx
> +}
I see what you did here with the fontawesome icons. But we agreed that we will be using Tailwind Elements and you can do this easily and it will look better also with this : https://tailwind-elements.com/docs/standard/components/accordion/

Please try and recreate this with this accordion.

2022-04-10 22:06 UTC, Iseluin commented on src/pages/__tests__/Faq.test.jsx
> +}));
Nice test, but you will have to redo these tests when you switch using the Tailwind Elements Accordion. Also, please  write your tests inside the component or page folder that you create.

2022-04-12 20:03 UTC, mustafadurmaz commented on .eslintrc.json
> +        "import/prefer-default-export": "off"
This exception has been removed.

2022-04-12 20:05 UTC, mustafadurmaz commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.18",
These dependencies has been removed. src/assets/images folder structure has been created.

2022-04-12 20:07 UTC, mustafadurmaz commented on src/index.js
>  import * as serviceWorker from './serviceWorker';
Imports are edited like this.

2022-04-12 20:08 UTC, mustafadurmaz commented on src/pages/Faq.jsx
> +import imagefaq from '../images/image-faq.png';
These have been removed.

2022-04-12 20:11 UTC, mustafadurmaz commented on src/pages/Faq.jsx
> +}
Faq page recreated using tailwinds-element accordion.

2022-04-12 20:12 UTC, mustafadurmaz commented on src/pages/__tests__/Faq.test.jsx
> +}));
Test was edited according to the new page.

2022-04-13 14:49 UTC, Iseluin requested changes
Gorgeous work @mustafadurmaz, this page really looks great and there are no errors on the responsivity also. I'm impressed. 2 small issues and we can merge this.

- Please put your FAQ Page Component in src/pages/FAQ/-your file here- and please put the tests of it inside the same folder too.
- Please update your branch from the dev branch, deal with the merge conflicts and push again.

Then we will be good to merge.

2022-04-15 13:34 UTC, maqalaqil requested changes
amazing job @mustafadurmaz  
just try to fix the eslint errors

2022-04-16 18:40 UTC, merged