Homepage
ReCoded-Org/capstone-turkey-react-paying-it-forward pull request #18
Opened 2022-04-14 07:44 UTC by khadijahawa

finished developing and designing the home page with 4 sections 
it is fully responsive
made a file structure for importing the sections into the home page 
used 2 libraries material UI and react slider 
pulled the dev branch in order to get the updates and solve the conflicts 
//I couldn't include a screenshot for the page fully

2022-04-15 13:01 UTC, maqalaqil approved these changes
LGTM @khadijahawa great job!

2022-04-21 15:18 UTC, Iseluin requested changes
1- Please put the images in assets/images. If you want, you can create a Home folder in it to put the images used in the homepage.
2- What is the purpose of the "app" folder?

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Hero/Hero.jsx
> +import { IoIosArrowBack, IoIosArrowForward } from 'react-icons/io';
Please leave a blank line after those global imports.

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Team/Team.jsx
> +      department: 'Web developer',
Please pay attention to the capital letters. It should be Web Developer.

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Team/Team.jsx
> +  const memebers = [
"Members"

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Team/Team.jsx
> +      // twitter: twitter,
We wont need those so delete them. But add our githubs please.

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Team/Team.jsx
> +      name: 'Khadija',
Let's use full names.

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Team/Team.jsx
> +  ];
Same as above comments.

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Testimonial/Testimonial.jsx
> +// import { IoIosArrowBack, IoIosArrowForward } from 'react-icons/io';
Delete this if we are not going to use them.

2022-04-21 15:18 UTC, Iseluin commented on src/components/HomeSections/Testimonial/Testomonial.css
> +} */
Why are those commented out? Delete them if you are not going to use them.

2022-04-21 15:18 UTC, Iseluin commented on src/index.js
> +import 'tw-elements';
Global import to the top please.

2022-04-27 08:53 UTC, merged